// frontend/angular/src/app/components/login/login.component.ts
import { HttpResponse } from '@angular/common/http';
import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { AuthenticationRequest } from 'src/app/models/authentication-request';
import { AuthenticationService } from 'src/app/services/authentication/authentication.service';

@Component({
  selector: 'app-login',
  templateUrl: './login.component.html',
  styleUrls: ['./login.component.scss']
})
export class LoginComponent {
  authenticationRequest: AuthenticationRequest = {};
  errorMsg = ''

  constructor(
    private authenticationService: AuthenticationService,
    private router: Router
  ) { }

  login(){
    this.errorMsg = '';
    this.authenticationService.login(this.authenticationRequest)
    .subscribe({
      next: (res: HttpResponse<any>) =>{
        console.log(res.headers.get('Authorization'));
        localStorage.setItem('access_token', res.headers.get('Authorization')!);
        this.router.navigate(['/customers']);
        
      },
      error: (err) =>{
        if(err.error.statusCode === 401){
          this.errorMsg = 'Login and/or password is incorrect'
        }
        
      }
    })
  }

  register(){
    this.router.navigate(['/register']);
  }

}

<div class="flex" style="height: 98vh">
  <div class="col-6 flex flex-column justify-content-center">
    <div class="m-auto">
      <div class="text-center">
        <p-avatar
          [style]="{ width: '380px', height: '120px' }"
          image="/assets/sunat-logo.png"
          class="mr-2"
          size="xlarge"
        />
        <h1>Sign in to your account</h1>
      </div>
      
      <p-message 
      *ngIf="errorMsg"
      severity="error" 
      [text]="errorMsg"
      styleClass="mb-2"
      ></p-message>
      
      <div class="field">
        <label for="email">Email</label>
        <input
          [(ngModel)]="authenticationRequest.username"
          id="email"
          pInputText
          placeholder="jane@gmail.com"
          type="email"
          class="w-full"
        />
      </div>
      <div class="field">
        <label for="password">Password</label>
        <input
        [(ngModel)]="authenticationRequest.password"
          id="password"
          pInputText
          placeholder="password"
          type="password"
          class="w-full"
        />
      </div>
      <button 
      pButton 
      label="Login" 
      class="w-full"
      (click)="login()"
      ></button>
      <button
        pButton
        label="Don't have an account? Signup now."
        class="w-full p-button-link text-left pl-0"
        (click)="register()"
      ></button>
    </div>
  </div>
  <div
    class="col-6 p-0 m-0 flex flex-column justify-content-center align-items-center right-container"
  >
    <img
      class="background p-0"
      src="https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1352&q=80"
    />
  </div>
</div>

// frontend/react/src/components/login/Login.jsx
import {
  Button,
  Flex,
  FormLabel,
  Heading,
  Input,
  Stack,
  Image,
  Box,
  Alert,
  AlertIcon,
} from "@chakra-ui/react";
import logo from "../../assets/sunat-logo.png";
import { Formik, Form, useField } from "formik";
import * as Yup from "yup";
import { useAuth } from "../context/AuthContext";
import { errorNotification } from "../../services/notification";
import { Link, useNavigate } from "react-router-dom";
import { useEffect } from "react";

const MyTextInput = ({ label, ...props }) => {
  // useField() returns [formik.getFieldProps(), formik.getFieldMeta()]
  // which we can spread on <input>. We can use field meta to show an error
  // message if the field is invalid and it has been touched (i.e. visited)
  const [field, meta] = useField(props);
  return (
    <Box>
      <FormLabel htmlFor={props.id || props.name}>{label}</FormLabel>
      <Input className="text-input" {...field} {...props} />
      {meta.touched && meta.error ? (
        <Alert className="error" status={"error"} mt={2}>
          <AlertIcon />
          {meta.error}
        </Alert>
      ) : null}
    </Box>
  );
};

const LoginForm = () => {
  const { login } = useAuth();
  const navigate =useNavigate();

  return (
    <Formik
      validateOnMount={true}
      validationSchema={Yup.object({
        username: Yup.string()
          .email("Must be valida email")
          .required("Email is required"),
        password: Yup.string()
          .max(20, "Password cannot be more than 20 characteres")
          .required("Password is required"),
      })}
      initialValues={{ username: "", password: "" }}
      onSubmit={(values, { setSubmitting }) => {
        setSubmitting(true);
        login(values)
          .then((res) => {
            //TODO: navigate to dashboard
            navigate("/dashboard");
            console.log("successfully login");
          })
          .catch((err) => {
            errorNotification(err.code, err?.response.data.message);
          })
          .finally(() => {
            setSubmitting(false);
          });
      }}
    >
      {({ isValid, isSubmitting, dirty }) => (
        <Form>
          <Stack spacing={15}>
            <MyTextInput
              label={"Email"}
              name={"username"}
              type={"email"}
              placeholder={"hello@gmail.com"}
            />

            <MyTextInput
              label={"Password"}
              name={"password"}
              type={"password"}
              placeholder={"Type your password"}
            />

            <Button
              isDisabled={!dirty || !isValid || isSubmitting}
              type="submit"
            >
              Login
            </Button>
          </Stack>
        </Form>
      )}
    </Formik>
  );
};
const Login = () => {

  const { customer } = useAuth();
  const navigate = useNavigate();

  useEffect(() => {
    if (customer) {
      navigate("/dashboard");
    }
  });

  return (
    <Stack minH={"100vh"} direction={{ base: "column", md: "row" }}>
      <Flex p={8} flex={1} alignItems={"center"} justifyContent={"center"}>
        <Stack spacing={4} w={"full"} maxW={"md"}>
          <Image src={logo} alt={"Sunat Logo"} />
          <Heading fontSize={"2xl"} mb={15}>
            Sign in to your account
          </Heading>
          <LoginForm />
          <Link color={"blue.500"} to={"/signup"}>Don&apos;t have an account? Signup now.</Link>
        </Stack>
      </Flex>
      <Flex flex={1}>
        <Image
          alt={"Login Image"}
          objectFit={"cover"}
          src={
            "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1352&q=80"
          }
        />
      </Flex>
    </Stack>
  );
};

export default Login;
